
import { Bias, Category, Difficulty } from './types';

export const BIASES: Bias[] = [
    { id: 'confirmation-bias', name: 'Confirmation Bias', category: Category.BELIEF, definition: 'The tendency to search for, interpret, and recall information that supports one\'s prior beliefs.', example: 'A manager ignores successful reports from a remote worker but highlights a single missed email to prove remote work fails.', counterStrategy: 'Actively seek out "disconfirming" evidence. Play devil\'s advocate against your own ideas.', relatedBiases: ['anchoring', 'belief-perseverance'], difficulty: Difficulty.BEGINNER },
    { id: 'anchoring-bias', name: 'Anchoring Bias', category: Category.DECISION_MAKING, definition: 'Relying too heavily on the first piece of information offered (the "anchor") when making decisions.', example: 'Seeing a shirt for $100 makes a $50 shirt seem cheap, even if $50 is expensive for that shirt.', counterStrategy: 'Establish your own criteria/value before looking at the provided numbers.', relatedBiases: ['framing-effect'], difficulty: Difficulty.BEGINNER },
    { id: 'sunk-cost-fallacy', name: 'Sunk Cost Fallacy', category: Category.DECISION_MAKING, definition: 'Continuing an endeavor because of previously invested resources (time, money), rather than future value.', example: 'Finishing a boring book just because you read the first 100 pages.', counterStrategy: 'Ask: "If I hadn\'t invested anything yet, would I start this today?"', relatedBiases: ['loss-aversion'], difficulty: Difficulty.INTERMEDIATE },
    { id: 'fundamental-attribution-error', name: 'Fundamental Attribution Error', category: Category.SOCIAL, definition: 'Overemphasizing personality-based explanations for others\' behavior while underemphasizing situational explanations.', example: 'Thinking someone is lazy because they are late, rather than considering there might be traffic.', counterStrategy: 'Look for situational factors first. Give others the benefit of the doubt.', relatedBiases: ['self-serving-bias'], difficulty: Difficulty.INTERMEDIATE },
    { id: 'availability-heuristic', name: 'Availability Heuristic', category: Category.DECISION_MAKING, definition: 'Overestimating the importance of information that is available (recent or emotional).', example: 'Thinking plane crashes are more common than car crashes because they are reported more in the news.', counterStrategy: 'Look for statistics and base rates rather than relying on examples that come to mind.', relatedBiases: ['recency-bias', 'negativity-bias'], difficulty: Difficulty.BEGINNER },
    { id: 'dunning-kruger-effect', name: 'Dunning-Kruger Effect', category: Category.SOCIAL, definition: 'People with low ability at a task overestimate their ability.', example: 'An amateur chess player thinking they can beat a grandmaster because they know how the pieces move.', counterStrategy: 'Seek feedback from others and be open to criticism. Keep learning.', relatedBiases: ['overconfidence-effect'], difficulty: Difficulty.INTERMEDIATE },
    { id: 'halo-effect', name: 'Halo Effect', category: Category.SOCIAL, definition: 'The tendency for an impression created in one area to influence opinion in another area.', example: 'Assuming a physically attractive person is also kind and intelligent.', counterStrategy: 'Evaluate specific traits independently rather than forming a global impression.', relatedBiases: ['horn-effect'], difficulty: Difficulty.BEGINNER },
    { id: 'framing-effect', name: 'Framing Effect', category: Category.DECISION_MAKING, definition: 'Drawing different conclusions from the same information, depending on how that information is presented.', example: 'Preferring meat labeled "75% lean" over meat labeled "25% fat".', counterStrategy: 'Restate the information in different ways (e.g., look at the loss frame if presented with a gain frame).', relatedBiases: ['loss-aversion'], difficulty: Difficulty.BEGINNER },
    { id: 'hindsight-bias', name: 'Hindsight Bias', category: Category.BELIEF, definition: 'The tendency to perceive past events as having been more predictable than they actually were.', example: 'Saying "I knew it all along" after a stock market crash.', counterStrategy: 'Keep a decision journal to record your predictions and reasoning before events occur.', relatedBiases: ['outcome-bias'], difficulty: Difficulty.INTERMEDIATE },
    { id: 'gamblers-fallacy', name: 'Gambler\'s Fallacy', category: Category.DECISION_MAKING, definition: 'Believing that if a particular event occurs more frequently than normal during the past, it is less likely to happen in the future.', example: 'Thinking that after 5 heads in a row, the next coin toss must be tails.', counterStrategy: 'Remember that independent events (like coin tosses) have no memory.', relatedBiases: ['hot-hand-fallacy'], difficulty: Difficulty.BEGINNER },
    { id: 'status-quo-bias', name: 'Status Quo Bias', category: Category.DECISION_MAKING, definition: 'The preference for the current state of affairs; doing nothing or maintaining the current decision.', example: 'Keeping a subscription you don\'t use simply because it\'s already set up.', counterStrategy: 'Ask: "If I wasn\'t already in this situation, would I choose to enter it?"', relatedBiases: ['loss-aversion'], difficulty: Difficulty.BEGINNER },
    { id: 'self-serving-bias', name: 'Self-Serving Bias', category: Category.SOCIAL, definition: 'The tendency to attribute positive events to one\'s own character but attribute negative events to external factors.', example: 'Getting an A is "I\'m smart," but getting an F is "The teacher hates me."', counterStrategy: 'Accept responsibility for failures and look for external contributors to success.', relatedBiases: ['fundamental-attribution-error'], difficulty: Difficulty.INTERMEDIATE },
    { id: 'survivorship-bias', name: 'Survivorship Bias', category: Category.DECISION_MAKING, definition: 'Concentrating on the people or things that made it past some selection process and overlooking those that did not.', example: 'Looking at successful startups to find a formula for success, while ignoring failed startups that did the same things.', counterStrategy: 'Ask: "What about the failures? What data is missing?"', relatedBiases: ['availability-heuristic'], difficulty: Difficulty.ADVANCED },
    { id: 'loss-aversion', name: 'Loss Aversion', category: Category.DECISION_MAKING, definition: 'The tendency to prefer avoiding losses to acquiring equivalent gains.', example: 'Refusing to sell a losing stock because you don\'t want to realize the loss, hoping it bounces back.', counterStrategy: 'Evaluate the decision as if you didn\'t own the item. Would you buy it today?', relatedBiases: ['sunk-cost-fallacy', 'endowment-effect'], difficulty: Difficulty.INTERMEDIATE },
    { id: 'bandwagon-effect', name: 'Bandwagon Effect', category: Category.SOCIAL, definition: 'The tendency to do (or believe) things because many other people do (or believe) the same.', example: 'Buying a specific brand of phone just because everyone else has one.', counterStrategy: 'Pause and ask if you actually want/need the item or idea, independent of others.', relatedBiases: ['groupthink'], difficulty: Difficulty.BEGINNER },
    { id: 'decoy-effect', name: 'Decoy Effect', category: Category.DECISION_MAKING, definition: 'The phenomenon where consumers will tend to have a specific change in preference between two options when also presented with a third option that is asymmetrically dominated.', example: 'Popcorn sizes: Small $3, Large $7. Adding a Medium for $6.50 makes the Large look like a steal.', counterStrategy: 'Ignore the options you wouldn\'t choose. Compare items on their own merits.', relatedBiases: ['anchoring-bias'], difficulty: Difficulty.ADVANCED },
    { id: 'planning-fallacy', name: 'Planning Fallacy', category: Category.DECISION_MAKING, definition: 'The tendency to underestimate the time, costs, and risks of future actions and at the same time overestimate the benefits.', example: 'Thinking you can write a term paper in one night.', counterStrategy: 'Use "reference class forecasting": look at how long similar tasks took in the past.', relatedBiases: ['optimism-bias'], difficulty: Difficulty.INTERMEDIATE },
    { id: 'zero-risk-bias', name: 'Zero-Risk Bias', category: Category.DECISION_MAKING, definition: 'Preference for reducing a small risk to zero over a greater reduction in a larger risk.', example: 'Paying a premium to eliminate the 1% risk of a minor issue rather than reducing a 10% risk of a major issue to 5%.', counterStrategy: 'Calculate the total expected value/impact of risk reduction.', relatedBiases: ['certainty-effect'], difficulty: Difficulty.ADVANCED },
    { id: 'parkinsons-law', name: "Parkinson's Law", category: Category.DECISION_MAKING, definition: 'Work expands so as to fill the time available for its completion.', example: 'Taking two weeks to finish a project that could be done in two days, just because the deadline is two weeks away.', counterStrategy: 'Set artificial, aggressive deadlines for yourself.', relatedBiases: ['planning-fallacy'], difficulty: Difficulty.BEGINNER }
];

export const INITIAL_STATE = {
  progress: {},
  dailyStreak: 0,
  lastStudyDate: null,
  totalXp: 0,
  favorites: [],
  preferences: {
    flashcardsOnlyFavorites: false,
    learnTab: 'all'
  }
};
